INSERT INTO category(name) VALUES ('silka')
INSERT INTO category(name) VALUES ('motoryzacja')
INSERT INTO category(name) VALUES ('muzyka')
INSERT INTO category(name) VALUES ('www')
INSERT INTO category(name) VALUES ('spotkanie')
INSERT INTO category(name) VALUES ('linux')
INSERT INTO users(username,email,password,roles) VALUES ('user2','user2@pb.edu.pl','1','ROLE_USER,ROLE_ADMIN')
INSERT INTO users(username,email,password,roles) VALUES ('user3','user3@pb.edu.pl','1','ROLE_USER,ROLE_ADMIN')
INSERT INTO note (title,category_id,content,www,date) VALUES ('note1',2,'Saaby są drogie w utrzymaniu','saab.com','2023-05-20')
INSERT INTO note (title,category_id,content,date) VALUES ('note3',3,'Blur wydaje nowy album','2018-06-20')
INSERT INTO note (title,category_id,content,www,date) VALUES ('note2',4,'Oasis recording info','oasis-recordinginfo.co.uk','2023-05-19')
INSERT INTO note (title,category_id,content,date) VALUES ('note4',2,'Saaby są drogie w utrzymaniu','2023-05-18')
INSERT INTO note (title,category_id,content,date) VALUES ('note5',2,'Amerykańskie są drogie w utrzymaniu','2023-05-22')
INSERT INTO note (title,category_id,content,date) VALUES ('note6',2,'W124 są drogie w utrzymaniu','2022-11-22')
INSERT INTO note (title,category_id,content,www,date) VALUES ('note7',4,'Chat','openai.com/blog/chatgpt','2023-05-24')
INSERT INTO note (title,category_id,content,date) VALUES ('note8',6,'Windows lepszy','2023-05-24')
INSERT INTO note (title,category_id,content,date) VALUES ('note9',5,'Spotkanie z Brajankiem jutro','2023-05-24')
INSERT INTO note (title,category_id,content,date) VALUES ('note10',1,'nowy rekord wyciskanie na klate 100kg','2023-05-24')
